### ISSUE TITLE
Request for lumen support

### ISSUE THREAD

**Issue by vaishnavmhetre** [designmynight/laravel-mongodb-passport#10]
Its good to know having a reliable support of Passport with MongoDb for Laravel, but I'm in need of this support for Lumen for my build.

**Comment by StevePorter92** [comment]
This package should support lumen out the box. What version are you using?

**Comment by vaishnavmhetre** [comment]
Lumen 5.6. The reason I have requested is, I'm going to use it over an enterprise app, hence concerned about the stability.

**Comment by StevePorter92** [comment]
Have you already tried using this package with Lumen 5.6? I can't see any reason why it would not work.

**Comment by vaishnavmhetre** [comment]
Yes. having no troubles yet. I thought having a deep dive into the source and making it rather official for Lumen would help.

**Comment by vaishnavmhetre** [comment]
Any official documentation made up for laravel so as to close the issue?

**Comment by StevePorter92** [comment]
@vaishnavmhetre this isn't an official Laravel package, so we will be unable to create official Laravel documentation unfortunately.

If you want to write some additional documentation for this package, please feel free to raise a pull request.
