### ISSUE TITLE
Please update packagist as well

### ISSUE THREAD

**Issue by susonwaiba** [designmynight/laravel-mongodb-passport#20]
hi, I am adding this package but seems like you have only updated your GIT repo.
So, Please update your https://packagist.org/packages/designmynight/laravel-mongodb-passport as well.
Thanks for packages. Great help

**Comment by matiaspub** [comment]
that's can help while we waitinghttps://www.sitepoint.com/quick-tip-composer-github-develop-packages-interactively/

**Comment by matiaspub** [comment]
Duplicate of #19
