### ISSUE TITLE
Error when try make request to endpoint /oauth/token 

### ISSUE THREAD

**Issue by javierdelgado1** [designmynight/laravel-mongodb-passport#33]
> BadMethodCallException: Call to undefined method DesignMyNight\Mongodb\Passport\Client::confidential() in file C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php on line 50

#0 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Support\Traits\ForwardsCalls.php(36): Illuminate\Database\Eloquent\Model::throwBadMethodCallException('confidential')
#1 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php(1618): Illuminate\Database\Eloquent\Model->forwardCallTo(Object(Jenssegers\Mongodb\Eloquent\Builder), 'confidential', Array)
#2 C:\xampp\htdocs\apirealtrends\vendor\jenssegers\mongodb\src\Jenssegers\Mongodb\Eloquent\Model.php(480): Illuminate\Database\Eloquent\Model->__call('confidential', Array)
#3 C:\xampp\htdocs\apirealtrends\vendor\laravel\passport\src\Bridge\ClientRepository.php(58): Jenssegers\Mongodb\Eloquent\Model->__call('confidential', Array)
#4 C:\xampp\htdocs\apirealtrends\vendor\league\oauth2-server\src\Grant\AbstractGrant.php(182): Laravel\Passport\Bridge\ClientRepository->validateClient('5e1a12356838000...', 'mqX2aTZaiQEu8wf...', 'password')
#5 C:\xampp\htdocs\apirealtrends\vendor\league\oauth2-server\src\Grant\PasswordGrant.php(52): League\OAuth2\Server\Grant\AbstractGrant->validateClient(Object(Laminas\Diactoros\ServerRequest))
#6 C:\xampp\htdocs\apirealtrends\vendor\league\oauth2-server\src\AuthorizationServer.php(198): League\OAuth2\Server\Grant\PasswordGrant->respondToAccessTokenRequest(Object(Laminas\Diactoros\ServerRequest), Object(League\OAuth2\Server\ResponseTypes\BearerTokenResponse), Object(DateInterval))
#7 C:\xampp\htdocs\apirealtrends\vendor\laravel\passport\src\Http\Controllers\AccessTokenController.php(63): League\OAuth2\Server\AuthorizationServer->respondToAccessTokenRequest(Object(Laminas\Diactoros\ServerRequest), Object(Laminas\Diactoros\Response))
#8 C:\xampp\htdocs\apirealtrends\vendor\laravel\passport\src\Http\Controllers\HandlesOAuthErrors.php(24): Laravel\Passport\Http\Controllers\AccessTokenController->Laravel\Passport\Http\Controllers\{closure}()
#9 C:\xampp\htdocs\apirealtrends\vendor\laravel\passport\src\Http\Controllers\AccessTokenController.php(65): Laravel\Passport\Http\Controllers\AccessTokenController->withErrorHandling(Object(Closure))
#10 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\ControllerDispatcher.php(48): Laravel\Passport\Http\Controllers\AccessTokenController->issueToken(Object(Laminas\Diactoros\ServerRequest))
#11 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Route.php(219): Illuminate\Routing\ControllerDispatcher->dispatch(Object(Illuminate\Routing\Route), Object(Laravel\Passport\Http\Controllers\AccessTokenController), 'issueToken')
#12 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Route.php(176): Illuminate\Routing\Route->runController()
#13 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Router.php(681): Illuminate\Routing\Route->run()
#14 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#15 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Middleware\ThrottleRequests.php(59): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Routing\Middleware\ThrottleRequests->handle(Object(Illuminate\Http\Request), Object(Closure))
#17 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Router.php(683): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Router.php(658): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#20 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Router.php(624): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#21 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Routing\Router.php(613): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(170): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(130): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#26 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\TransformsRequest.php(21): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#28 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#29 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode.php(63): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#32 C:\xampp\htdocs\apirealtrends\vendor\fideloper\proxy\src\TrustProxies.php(57): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(171): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#34 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Pipeline\Pipeline.php(105): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#35 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(145): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#36 C:\xampp\htdocs\apirealtrends\vendor\laravel\framework\src\Illuminate\Foundation\Http\Kernel.php(110): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\apirealtrends\public\index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#38 {main}

**Comment by javierdelgado1** [comment]
I resolve this problem with this package https://github.com/narwy/laravel-mongodb-passport

**Comment by alok20100** [comment]
> I resolve this problem with this package https://github.com/narwy/laravel-mongodb-passport

this url u have provided is not working redirect to 404 page

**Comment by F-Yousri** [comment]
https://github.com/narwy/laravel-mongodb-passport
has been either removed or migrated to a private repo unfortunately.

**Comment by javierdelgado1** [comment]
try in this url https://packagist.org/packages/narwy/laravel-mongodb-passport from packagist

**Comment by alok20100** [comment]
> try in this url https://packagist.org/packages/narwy/laravel-mongodb-passport from packagist

- Installing narwy/laravel-mongodb-passport (2.0.2): Cloning 9400665fc3
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is SHA256:nThbg6kXUpJWGl7E1IGOCspRomTxdCARLviKw6E5SY8.
Are you sure you want to continue connecting (yes/no)?

**Comment by alok20100** [comment]
> try in this url https://packagist.org/packages/narwy/laravel-mongodb-passport from packagist

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Failed to execute git clone --no-checkout 'https://***:***@github.com/narwy/laravel-mongodb-passport.git.git' '/vendor/narwy/laravel-mongodb-passport' && cd '/vendor/narwy/laravel-mongodb-passport'
  && git remote add composer 'https://***:***@github.com/narwy/laravel-mongodb-passport.git.git' && git fetch composer && git remote s
  et-url origin 'https://github.com/narwy/laravel-mongodb-passport.git.git' && git remote set-url composer 'https://github.com/narwy/l
  aravel-mongodb-passport.git.git'

  Cloning into '/vendor/narwy/laravel-mongodb-passport'...
  remote: Repository not found.
  fatal:***@github.com/narwy/laravel-mongodb-passport.git.git/' not found


require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
