### ISSUE TITLE
Support Passport 9

### ISSUE THREAD

**Issue by simonschaufi** [designmynight/laravel-mongodb-passport#41]
A new passport version 9 has been released. It would be great if this package could use the latest version as well.

**Comment by simonschaufi** [comment]
@designmynight ping

**Comment by simonschaufi** [comment]
@JasparGupta ping

**Comment by esron** [comment]
I'm waiting on this. It will solve this issue for me:

https://github.com/laravel/passport/issues/973

**Comment by esron** [comment]
I've opened a PR #45
