### ISSUE TITLE
Password grant client

### ISSUE THREAD

**Issue by plaffitt** [designmynight/laravel-mongodb-passport#5]
Hello, I'm developing a little app on Laravel with VueJs and MongoDB. I'm trying to figure out how to generate new password grant clients, but it seems impossible since the only way that I see to do so is using the command line `php artisan passport:client --password`. As long as I know, the command line of passport isn't compatible with this package.

I'm pretty sure that there is a way to use grant clients, what did I missed ?

**Comment by StevePorter92** [comment]
Hi @paullaffitte. It doesn't look like Laravel Passport comes with an endpoint to create your own password grant clients, unfortunately. It doesn't look like it would be too difficult to extend Passports ClientController functionality to allow you to do this. 

Here are some functions of interest.
https://github.com/laravel/passport/blob/5.0/src/Http/Controllers/ClientController.php#L59
https://github.com/laravel/passport/blob/5.0/src/Console/ClientCommand.php#L79
https://github.com/laravel/passport/blob/5.0/src/ClientRepository.php#L132

Hope this helps.
