### ISSUE TITLE
Will this work with Laravel 5.6 and Passport 5.0?

### ISSUE THREAD

**Issue by coreywelch** [designmynight/laravel-mongodb-passport#6]
Looked over the package and I don't see why it wouldn't work with Passport 5.0. However, I can't install this package because the composer.json required `jenssegers/mongodb@3.3.*` and `laravel/passport@4.0.*` which is preventing me from using this package.

**Comment by StevePorter92** [comment]
Thanks @coreywelch. I've updated the composer.json to support the  `jenssegers/mongodb@3.3.*` and `laravel/passport@4.0.*`.

**Comment by vsilva472** [comment]
@StevePorter92  Can you do this for passport@6.0.*?

**Comment by StevePorter92** [comment]
@vsilva472, this package will now support laravel passport 6
